import { useEffect, useState } from "react";
import axios from "axios";
import { Card, CardBody, Typography, Button } from "@material-tailwind/react";

export function Profile() {
  const [professor,setProfessor]=useState(null); const [form,setForm]=useState({}); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  useEffect(()=>{const id=localStorage.getItem("professorId"); if(!id)return setError("No professor session found."); axios.get(`http://localhost:8080/api/professors/${id}`).then(({data})=>{setProfessor(data);setForm({...data,password:"",subjects:(data.subjects||[]).join(", ")});localStorage.setItem("professorData",JSON.stringify(data));}).catch(e=>setError(e.response?.data||"Unable to load professor information."));},[]);
  if(!professor)return <div className="mt-12">{error||"Loading professor information..."}</div>;
  const save=async(e)=>{e.preventDefault();setMessage("");setError("");try{const {data}=await axios.put(`http://localhost:8080/api/professors/by-id/${professor.id}`,{...form,subjects:String(form.subjects||"").split(",").map(x=>x.trim()).filter(Boolean),password:form.password||undefined});setProfessor(data);setForm({...data,password:"",subjects:(data.subjects||[]).join(", ")});localStorage.setItem("professorData",JSON.stringify(data));setMessage("Profile updated successfully.");}catch(e){setError(e.response?.data||"Could not update profile.");}};
  return <div className="mt-8 space-y-6"><Card><CardBody><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-blue-500 text-2xl font-bold text-white">{professor.name?.charAt(0).toUpperCase()}</div><div><Typography variant="h4">{professor.name}</Typography><Typography color="blue-gray">Professor • {professor.departmentName}</Typography></div></div></CardBody></Card><Card><CardBody><Typography variant="h5" className="mb-4">My Information</Typography><form onSubmit={save} className="grid gap-4 md:grid-cols-2">{[["name","Name"],["professorId","Professor ID"],["departmentName","Department"],["subject","Primary Subject"],["username","Username"],["email","Email"],["subjects","Subjects (comma separated)"]].map(([k,l])=><label key={k} className="text-sm font-medium">{l}<input className="mt-1 w-full rounded-lg border px-3 py-2" value={form[k]||""} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label className="text-sm font-medium">New Password (optional)<input type="password" className="mt-1 w-full rounded-lg border px-3 py-2" value={form.password||""} onChange={e=>setForm({...form,password:e.target.value})}/></label><div className="md:col-span-2"><Button type="submit">Save Changes</Button></div></form>{message&&<p className="mt-4 text-green-600">{message}</p>}{error&&<p className="mt-4 text-red-600">{error}</p>}</CardBody></Card></div>;
}
export default Profile;
