import { Card, Input, Button, Typography } from "@material-tailwind/react";
import { Link, useNavigate } from "react-router-dom";
import { useState } from "react";
import axios from "axios";

export function ProfessorSignUp() {
  const [form,setForm]=useState({professorId:"",name:"",departmentName:"",subject:"",username:"",password:"",email:"",subjects:""});
  const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState(""); const navigate=useNavigate();
  const update=(k,v)=>setForm(p=>({...p,[k]:v}));
  const submit=async(e)=>{e.preventDefault();setError("");setSuccess("");if(Object.entries(form).some(([k,v])=>k!=="subjects"&&!String(v).trim()))return setError("Please fill in all required fields.");if(form.password.length<6)return setError("Password must be at least 6 characters long.");setLoading(true);try{await axios.post("http://localhost:8080/api/professors/add-prof",{...form,subjects:form.subjects.split(",").map(x=>x.trim()).filter(Boolean)});setSuccess("Professor registered successfully. You can sign in now.");setTimeout(()=>navigate("/auth/professor/sign-in"),700);}catch(e){setError(e.response?.data||"Error saving professor data.");}finally{setLoading(false);}};
  return <section className="m-4 flex justify-center"><Card className="w-full max-w-xl p-6"><div className="text-center"><Typography variant="h2" className="font-bold mb-2">Professor Sign Up</Typography><Typography color="blue-gray">Create a faculty account.</Typography></div><form className="mt-6 space-y-4" onSubmit={submit}><div className="grid gap-4 md:grid-cols-2"><Input label="Professor ID *" value={form.professorId} onChange={e=>update("professorId",e.target.value)} required/><Input label="Name *" value={form.name} onChange={e=>update("name",e.target.value)} required/><Input label="Department *" value={form.departmentName} onChange={e=>update("departmentName",e.target.value)} required/><Input label="Primary Subject *" value={form.subject} onChange={e=>update("subject",e.target.value)} required/><Input label="Username *" value={form.username} onChange={e=>update("username",e.target.value)} required/><Input label="Email *" type="email" value={form.email} onChange={e=>update("email",e.target.value)} required/><Input label="Subjects (comma separated)" value={form.subjects} onChange={e=>update("subjects",e.target.value)}/><Input label="Password *" type="password" value={form.password} onChange={e=>update("password",e.target.value)} required/></div><Button fullWidth type="submit" disabled={loading}>{loading?"Registering...":"Register Professor"}</Button>{error&&<p className="text-sm text-red-600">{error}</p>}{success&&<p className="text-sm text-green-600">{success}</p>}</form><Typography variant="small" color="gray" className="mt-4 flex justify-center">Already registered?<Link to="/auth/professor/sign-in" className="ml-1 font-bold text-blue-500">Sign In</Link></Typography></Card></section>;
}
export default ProfessorSignUp;
