import { useEffect, useState } from "react";
import axios from "axios";
import { Card, CardBody, Typography, Button } from "@material-tailwind/react";

const API = "http://localhost:8080/api";
const blankCourse = { code: "", name: "", credits: 4, professorId: "" };
const blankSubject = { id: null, code: "", name: "", credits: 4, grade: "", ct1: 0, ct2: 0, theory: 0, semesterId: "" };

export default function SemesterTable() {
  const [semesters, setSemesters] = useState([]); const [students, setStudents] = useState([]); const [professors, setProfessors] = useState([]); const [courses, setCourses] = useState([]);
  const [course, setCourse] = useState(blankCourse); const [semester, setSemester] = useState({ semester: "", studentId: "", courseId: "" }); const [subject, setSubject] = useState(blankSubject);
  const [selectedStudent, setSelectedStudent] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState("");

  const load = async () => { try { const [sem, st, p, c] = await Promise.all([axios.get(`${API}/semesters/all`), axios.get(`${API}/students`), axios.get(`${API}/professors/get-prof`), axios.get(`${API}/courses`)]); setSemesters(sem.data || []); setStudents(st.data || []); setProfessors(p.data || []); setCourses(c.data || []); } catch (e) { setError(e.response?.data || "Could not load academic records."); } };
  useEffect(() => { load(); }, []);
  const notice = (m, e = "") => { setMessage(m); setError(e); };

  const createCourse = async (e) => { e.preventDefault(); try { await axios.post(`${API}/courses/add`, { code: course.code, name: course.name, credits: Number(course.credits), professor: { id: Number(course.professorId) } }); setCourse(blankCourse); notice("Course created and assigned to the professor."); load(); } catch (e) { notice("", e.response?.data || "Could not create course."); } };
  const createSemester = async (e) => { e.preventDefault(); try { await axios.post(`${API}/semesters/add`, { semester: semester.semester, student: { id: Number(semester.studentId) }, course: { id: Number(semester.courseId) }, subjects: [], practicals: [] }); setSemester({ semester: "", studentId: "", courseId: "" }); notice("Semester record created. Add subjects below to make them visible to the student."); load(); } catch (e) { notice("", e.response?.data || "Could not create semester."); } };
  const saveSubject = async (e) => { e.preventDefault(); try { const payload = { code: subject.code, name: subject.name, credits: Number(subject.credits), grade: subject.grade || "Not graded", ct1: Number(subject.ct1 || 0), ct2: Number(subject.ct2 || 0), theory: Number(subject.theory || 0), semester: { id: Number(subject.semesterId) } }; if (subject.id) await axios.put(`${API}/subjects/${subject.id}`, payload); else await axios.post(`${API}/subjects/add`, payload); setSubject(blankSubject); notice(subject.id ? "Subject updated." : "Subject added. It is now part of that student's semester record."); load(); } catch (e) { notice("", e.response?.data || "Could not save subject."); } };
  const del = async (url, label) => { if (!window.confirm(`Delete this ${label}?`)) return; try { await axios.delete(url); notice(`${label} deleted.`); load(); } catch (e) { notice("", e.response?.data || `Could not delete ${label}.`); } };

  const visibleSemesters = selectedStudent ? semesters.filter(s => s.student?.id === Number(selectedStudent)) : semesters;
  const selectedName = students.find(s => s.id === Number(selectedStudent));

  return <div className="mt-8 space-y-6">
    <div><Typography variant="h4">Academic Records</Typography><Typography color="blue-gray">Create real course, semester and subject records. Nothing is pre-filled with demo marks or demo subjects.</Typography></div>
    {(message || error) && <div className={`rounded p-3 text-sm ${error ? "bg-red-50 text-red-700" : "bg-green-50 text-green-700"}`}>{error || message}</div>}

    <Card><CardBody><Typography variant="h5" className="mb-4">1. Courses</Typography><form onSubmit={createCourse} className="grid gap-3 md:grid-cols-4"><input className="rounded border p-2" placeholder="Course code" value={course.code} onChange={e => setCourse({...course, code:e.target.value})} required /><input className="rounded border p-2" placeholder="Subject / course name" value={course.name} onChange={e => setCourse({...course, name:e.target.value})} required /><input className="rounded border p-2" type="number" min="1" max="10" placeholder="Credits" value={course.credits} onChange={e => setCourse({...course, credits:e.target.value})} required /><select className="rounded border p-2" value={course.professorId} onChange={e => setCourse({...course, professorId:e.target.value})} required><option value="">Assign professor</option>{professors.map(p => <option key={p.id} value={p.id}>{p.name} ({p.professorId})</option>)}</select><div className="md:col-span-4"><Button type="submit">Add Course</Button></div></form></CardBody></Card>

    <Card><CardBody><Typography variant="h5" className="mb-2">2. Assign a Semester to a Student</Typography><Typography variant="small" color="blue-gray" className="mb-4 block">A student sees only semester records assigned to their account.</Typography><form onSubmit={createSemester} className="grid gap-3 md:grid-cols-3"><select className="rounded border p-2" value={semester.studentId} onChange={e=>setSemester({...semester,studentId:e.target.value})} required><option value="">Select student</option>{students.map(s=><option key={s.id} value={s.id}>{s.studName} {s.studLastName} ({s.studentId})</option>)}</select><select className="rounded border p-2" value={semester.courseId} onChange={e=>setSemester({...semester,courseId:e.target.value})} required><option value="">Select course</option>{courses.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select><select className="rounded border p-2" value={semester.semester} onChange={e=>setSemester({...semester,semester:e.target.value})} required><option value="">Select semester</option>{[1,2,3,4,5,6,7,8].map(n=><option key={n}>Semester {n}</option>)}</select><div className="md:col-span-3"><Button type="submit">Create Semester Record</Button></div></form></CardBody></Card>

    <Card><CardBody><Typography variant="h5" className="mb-2">3. Add Subjects to a Semester</Typography><Typography variant="small" color="blue-gray" className="mb-4 block">These are the subjects students will actually see. There are no built-in demo subjects.</Typography><form onSubmit={saveSubject} className="grid gap-3 md:grid-cols-4"><select className="rounded border p-2" value={subject.semesterId} onChange={e=>setSubject({...subject,semesterId:e.target.value})} required><option value="">Select semester/student</option>{semesters.map(s=><option key={s.id} value={s.id}>{s.semester} — {s.student?.studName || "Student"}</option>)}</select><input className="rounded border p-2" placeholder="Subject code" value={subject.code} onChange={e=>setSubject({...subject,code:e.target.value})} required /><input className="rounded border p-2" placeholder="Subject name" value={subject.name} onChange={e=>setSubject({...subject,name:e.target.value})} required /><input className="rounded border p-2" type="number" min="1" value={subject.credits} onChange={e=>setSubject({...subject,credits:e.target.value})} placeholder="Credits" required /><input className="rounded border p-2" placeholder="Grade (optional)" value={subject.grade} onChange={e=>setSubject({...subject,grade:e.target.value})} /><input className="rounded border p-2" type="number" min="0" value={subject.ct1} onChange={e=>setSubject({...subject,ct1:e.target.value})} placeholder="CT-1" /><input className="rounded border p-2" type="number" min="0" value={subject.ct2} onChange={e=>setSubject({...subject,ct2:e.target.value})} placeholder="CT-2" /><input className="rounded border p-2" type="number" min="0" value={subject.theory} onChange={e=>setSubject({...subject,theory:e.target.value})} placeholder="Theory" /><div className="md:col-span-4 flex gap-2"><Button type="submit">{subject.id ? "Update Subject" : "Add Subject"}</Button>{subject.id && <Button type="button" variant="outlined" onClick={()=>setSubject(blankSubject)}>Cancel</Button>}</div></form></CardBody></Card>

    <Card><CardBody><Typography variant="h5" className="mb-4">Student Semester Details</Typography><select className="mb-5 w-full rounded border p-2 md:w-1/2" value={selectedStudent} onChange={e=>setSelectedStudent(e.target.value)}><option value="">All students</option>{students.map(s=><option key={s.id} value={s.id}>{s.studName} {s.studLastName} ({s.studentId})</option>)}</select>{selectedName && <Typography className="mb-4" color="blue-gray">Showing academic records for <b>{selectedName.studName} {selectedName.studLastName}</b> — {selectedName.major}, Year {selectedName.year}</Typography>}
      {visibleSemesters.length === 0 ? <Typography color="blue-gray">No semester records found. Create a semester record above.</Typography> : <div className="space-y-4">{visibleSemesters.map(s=><div key={s.id} className="rounded-lg border p-4"><div className="flex items-start justify-between gap-3"><div><Typography variant="h6">{s.semester}</Typography><Typography variant="small" color="blue-gray">{s.student?.studName || "Student"} • {s.course?.code || "Course"} — {s.course?.name || "Not assigned"}{s.course?.professor?.name ? ` • ${s.course.professor.name}` : ""}</Typography></div><Button size="sm" color="red" onClick={()=>del(`${API}/semesters/${s.id}`,"semester")}>Delete</Button></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead><tr>{['Code','Subject','Credits','CT1','CT2','Theory','Grade','Action'].map(h=><th key={h} className="border-b p-2 text-xs">{h}</th>)}</tr></thead><tbody>{(s.subjects || []).map(sub=><tr key={sub.id} className="border-b"><td className="p-2">{sub.code}</td><td className="p-2">{sub.name}</td><td className="p-2">{sub.credits}</td><td className="p-2">{sub.ct1}</td><td className="p-2">{sub.ct2}</td><td className="p-2">{sub.theory}</td><td className="p-2">{sub.grade || "Not graded"}</td><td className="p-2"><div className="flex gap-2"><Button size="sm" variant="outlined" onClick={()=>setSubject({...sub, semesterId:s.id})}>Edit</Button><Button size="sm" color="red" onClick={()=>del(`${API}/subjects/${sub.id}`,"subject")}>Delete</Button></div></td></tr>)}</tbody></table></div>{(!s.subjects || s.subjects.length===0) && <Typography className="mt-3 text-sm" color="blue-gray">No subjects added yet.</Typography>}</div>)}</div>}
    </CardBody></Card>
  </div>;
}
